title: Overland Country Bar & Grill
author: Paul Hayward & Steven Kirkish
tagline: Oakland's only country bar, featuring live music, line dancing classes, Warriors games, food, drinks and fun.
url: http://overlandoakland.com
logo: /assets/img/overland.svg


timezone: US/Pacific

gems:
    - jekyll-sitemap


bootstrap: business-frontpage-1.0.3.css
