title: Overland Country Bar & Restaurant
type: BarOrPub

url: http://overlandoakland.com
logo: /assets/img/overland.svg

timezone: US/Pacific

gems:
  - jekyll-sitemap


bootstraps:
  - theme: business-frontpage-1.0.3.css
